name: transport_bin
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.6.0
  transport:
    path: /Users/wangyanxiong/Documents/IDEAProject/transport
  console_cmd: ^1.0.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
